/// Flutter icons PiggyBank
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PiggyBank
///      fonts:
///       - asset: fonts/PiggyBank.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PiggyBank {
  PiggyBank._();

  static const _kFontFam = 'PiggyBank';
  static const String _kFontPkg = null;

  static const IconData piggy_black = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggy_white = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
